# Etapa de construcción
FROM openjdk:21

COPY ./target/TuCine-0.0.1-SNAPSHOT.jar /

RUN sh -c 'touch TuCine-0.0.1-SNAPSHOT.jar'

ENTRYPOINT ["java","-jar","/TuCine-0.0.1-SNAPSHOT.jar"]

RUN chmod +x /TuCine-0.0.1-SNAPSHOT.jar 